services:
    nginx-proxy:
      build: nginx-proxy
      ports:
        - 80:80
          #- 8080:80
      depends_on:
        - frontend
        - api
        - worker
        - fileserver
    frontend:
        build: frontend
        command: yarn start-docker
        ports:
            - 3000:3000
        restart: on-failure
        volumes:
            - ./frontend/src:/opt/frontend/src
            - ./appdata:/opt/appdata
            - ./frontend/vite.config.js:/opt/frontend/vite.config.js
            - ./frontend/index.html:/opt/frontend/index.html
        secrets:
            - source: frontend-api-keys
              target: .env
    api:
        build: server
        ports:
            - 8000:8000
        restart: on-failure
        volumes:
            - ./server:/opt/server
            - ./appdata:/opt/appdata
    worker:
        build: backend-worker
        command: /opt/conda/bin/python /opt/worker/worker.py api 8000 /opt/appdata
        restart: on-failure
        volumes:
            - ./backend-worker:/opt/worker
            - ./appdata:/opt/appdata
    fileserver:
        image: nginx:mainline
        restart: on-failure
        ports:
            - 9000:9000
        volumes:
            - ./fileserver/app.conf:/etc/nginx/conf.d/default.conf
            - ./appdata:/opt/appdata

secrets:
    frontend-api-keys:
        file: ./frontend/.env

